### ISSUE TITLE
[1] - 关于Scrapy Framework的安装问题

### ISSUE THREAD

**Issue by Aisuko** [PyCN/dianping_data#2]
win10 x64 python2.7 ,本地电脑现有vs2008和vs2015，但是安装最后提示c++存在问题，研究好久没有解决，你们碰见过吗？

**Comment by Lorryrui** [comment]
截图给我看下 应该是环境问题。提示c++ 我是遇到过的，你把报错给我看看。

**Comment by Lving** [comment]
百度出错的最后一行， 需要安装一个微软的组件

**Comment by Aisuko** [comment]
![default](https://cloud.githubusercontent.com/assets/8053949/19597544/cde9a31c-97c7-11e6-8f22-06f1aa97e3da.png)

**Comment by Lorryrui** [comment]
这个我之前也是遇到过的，缺了一个依赖。你有装过win32py吗。。这个报错网上应该有解决办法的，我当时也是在网上搜的

**Comment by Aisuko** [comment]
好的，我去安装一下，这个应该是没有安装过

**Comment by Aisuko** [comment]
ok,确实是pywin32的问题，谢谢 @Lorryrui
